services:
  postgres:
    image: postgres:16
    container_name: ticbnpick-postgres
    env_file:
      - .env
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticbnpick-net

volumes:
  postgres_data:

networks:
  ticbnpick-net:
    driver: bridge